services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATA_DIR: /data
      PORT: "8000"
      TZ: Europe/Berlin
    volumes:
      - pvdata:/data

  daily:
    build: .
    profiles: ["job"]
    environment:
      DATA_DIR: /data
      TZ: Europe/Berlin
    volumes:
      - pvdata:/data
    command: ["daily"]

volumes:
  pvdata:
